### ISSUE TITLE
Q: Project Scope

### ISSUE THREAD

**Issue by mwittig** [ckrey/mqtt-esp#3]
Hi, I have just come across your project space and I am wondering whether or not this is about implementing a mqtt broker on esp. If it is about implementing a mqtt client have a look at ESPeasy <http://www.esp8266.nu/index.php/ESPEasy>

**Comment by marvinroger** [comment]
Hi! This library is going to be a MQTT client. I see ESPEasy is using PubSubClient from knolleary, which is great but not always stable, depending on the context. The goal here is to implement a fully asynchronous MQTT client using [ESPAsyncTCP](https://github.com/me-no-dev/ESPAsyncTCP).

**Comment by mwittig** [comment]
Thanks for the swift reply! Sounds intersting to me.
